enum NETWORK_PACKETS
{
	CLIENT_PLAYER_INPUT,
	SERVER_PLAYER_INPUT,
	CLIENT_PLAYER_VISUALS,
	SERVER_PLAYER_VISUALS,
	PLAYER_POSITION,
	PLAYER_POINTS,
	
	SYNC_PLAYERS,
	SPAWN_SELF,
	SPAWN_OTHER,
	
	BALL_SYNC,
	
	//Tank control
	CLIENT_CONTROL_TANK,
	SERVER_CONTROL_TANK
}